DATA_SETS = "./data"
DATA_SETS_BRUTOS = f"{DATA_SETS}/brutos"
DATA_SETS_LIMPOS = f"{DATA_SETS}/limpos"
DATA_SETS_RESUMOS = f"{DATA_SETS}/resumos"

DATA_SET_EMISSION = f"{DATA_SETS_LIMPOS}/emissoes_co2.parquet"
DATA_SET_PIB = f"{DATA_SETS_LIMPOS}/PIB.parquet"
DATA_SET_PRODUCAO = f"{DATA_SETS_LIMPOS}/producao_total_e_area.parquet"
DATA_SET_FERTILIZANTES = f"{DATA_SETS_LIMPOS}/fertilizantes_total.parquet"
DATA_SET_PESTICIDAS = f"{DATA_SETS_LIMPOS}/pesticidas_total.parquet"