country_codes_temperatura = {
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Angola': 'AGO',
    'Antarctica': 'ATA',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bolivia': 'BOL',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Brazil': 'BRA',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burma': 'MMR',  # Código ISO para Mianmar
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cape Verde': 'CPV',
    'Central African Republic': 'CAF',
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Congo (Brazzaville)': 'COC',
    'Congo (Kinshasa)': 'COD',
    'Costa Rica': 'CRI',
    "Cote D'Ivoire": 'CIV',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Denmark': 'DNK',
    'Dominican Republic': 'DOM',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Ethiopia': 'ETH',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'Gabon': 'GAB',
    'Gambia': 'GMB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guatemala': 'GTM',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Honduras': 'HND',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Korea, North': 'PRK',
    'Korea, South': 'KOR',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    'Laos': 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Malaysia': 'MYS',
    'Malawi': 'MWI',
    'Malta': 'MLT',
    'Mexico': 'MEX',
    'Moldova': 'MDA',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Namibia': 'NAM',
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syria': 'SYR',
    'Taiwan': 'TWN',
    'Tajikistan': 'TJK',
    'Tanzania': 'TZA',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tonga': 'TON',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Turkmenistan': 'TKM',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United States': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Qatar': 'QAT',
    'Rwanda': 'RWA',
    'Burundi': 'BDI',
    'Maldives': 'MDV',
    'Brunei': 'BRN',
    'Swaziland': 'SWZ',
    'Hong Kong': 'HKG',
    'Equatorial Guinea': 'GNQ'
    }

country_codes_faostat = {
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Angola': 'AGO',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bolivia': 'BOL',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Brazil': 'BRA',
    'Brunei Darussalam': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Central African Republic': 'CAF',
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Congo': 'COG',
    'Costa Rica': 'CRI',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    "Côte d'Ivoire": 'CIV',
    'Democratic Republic of the Congo': 'COD',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominican Republic': 'DOM',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'Gabon': 'GAB',
    'Gambia': 'GMB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Greece': 'GRC',
    'Grenada': 'GRD',
    'Guatemala': 'GTM',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Honduras': 'HND',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Mexico': 'MEX',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Romania': 'ROU',
    'Russian Federation': 'RUS',
    'Rwanda': 'RWA',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Samoa': 'WSM',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syrian Arab Republic': 'SYR',
    'Tajikistan': 'TJK',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tonga': 'TON',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE',
    'United Kingdom of Great Britain and Northern Ireland': 'GBR',
    'United States of America': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'World': 'WLD',
    'USSR': 'SUN',
    'Yugoslav SFR': 'YUG'
    }

countries_codes_worldbank = {
    'Aruba': 'ABW',
    'Afghanistan': 'AFG',
    'Angola': 'AGO',
    'Albania': 'ALB',
    'Andorra': 'AND',
    'United Arab Emirates': 'ARE',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'American Samoa': 'ASM',
    'Antigua and Barbuda': 'ATG',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Burundi': 'BDI',
    'Belgium': 'BEL',
    'Benin': 'BEN',
    'Burkina Faso': 'BFA',
    'Bangladesh': 'BGD',
    'Bulgaria': 'BGR',
    'Bahrain': 'BHR',
    'Bahamas, The': 'BHS',
    'Bosnia and Herzegovina': 'BIH',
    'Belarus': 'BLR',
    'Belize': 'BLZ',
    'Bermuda': 'BMU',
    'Bolivia': 'BOL',
    'Brazil': 'BRA',
    'Barbados': 'BRB',
    'Brunei Darussalam': 'BRN',
    'Bhutan': 'BTN',
    'Botswana': 'BWA',
    'Central African Republic': 'CAF',
    'Canada': 'CAN',
    'Switzerland': 'CHE',
    'Channel Islands': 'CHI',  # Not an ISO member, placeholder
    'Chile': 'CHL',
    'China': 'CHN',
    "Cote d'Ivoire": 'CIV',
    'Cameroon': 'CMR',
    'Congo, Dem. Rep.': 'COD',
    'Congo, Rep.': 'COG',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Cabo Verde': 'CPV',
    'Costa Rica': 'CRI',
    'Cuba': 'CUB',
    'Curacao': 'CUW',
    'Cayman Islands': 'CYM',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Germany': 'DEU',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Denmark': 'DNK',
    'Dominican Republic': 'DOM',
    'Algeria': 'DZA',
    'Ecuador': 'ECU',
    'Egypt, Arab Rep.': 'EGY',
    'Spain': 'ESP',
    'Estonia': 'EST',
    'Ethiopia': 'ETH',
    'Finland': 'FIN',
    'Fiji': 'FJI',
    'France': 'FRA',
    'Faroe Islands': 'FRO',
    'Gabon': 'GAB',
    'United Kingdom': 'GBR',
    'Georgia': 'GEO',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Guinea': 'GIN',
    'Gambia, The': 'GMB',
    'Guinea-Bissau': 'GNB',
    'Equatorial Guinea': 'GNQ',
    'Greece': 'GRC',
    'Grenada': 'GRD',
    'Greenland': 'GRL',
    'Guatemala': 'GTM',
    'Guam': 'GUM',
    'Guyana': 'GUY',
    'Hong Kong SAR, China': 'HKG',
    'Honduras': 'HND',
    'Croatia': 'HRV',
    'Haiti': 'HTI',
    'Hungary': 'HUN',
    'Indonesia': 'IDN',
    'Isle of Man': 'IMN',
    'India': 'IND',
    'Ireland': 'IRL',
    'Iran, Islamic Rep.': 'IRN',
    'Iraq': 'IRQ',
    'Iceland': 'ISL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Jordan': 'JOR',
    'Japan': 'JPN',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kyrgyz Republic': 'KGZ',
    'Cambodia': 'KHM',
    'Kiribati': 'KIR',
    'St. Kitts and Nevis': 'KNA',
    'Korea, Rep.': 'KOR',
    'Kuwait': 'KWT',
    'Lao PDR': 'LAO',
    'Lebanon': 'LBN',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'St. Lucia': 'LCA',
    'Liechtenstein': 'LIE',
    'Sri Lanka': 'LKA',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Latvia': 'LVA',
    'Macao SAR, China': 'MAC',
    'St. Martin (French part)': 'MAF',  # Not an ISO member, placeholder
    'Morocco': 'MAR',
    'Monaco': 'MCO',
    'Moldova': 'MDA',
    'Madagascar': 'MDG',
    'Maldives': 'MDV',
    'Mexico': 'MEX',
    'Marshall Islands': 'MHL',
    'North Macedonia': 'MKD',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Myanmar': 'MMR',
    'Montenegro': 'MNE',
    'Mongolia': 'MNG',
    'Northern Mariana Islands': 'MNP',
    'Mozambique': 'MOZ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Namibia': 'NAM',
    'New Caledonia': 'NCL',  # Not an ISO member, placeholder
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'Nicaragua': 'NIC',
    'Netherlands': 'NLD',
    'Norway': 'NOR',
    'Nepal': 'NPL',
    'Nauru': 'NRU',
    'New Zealand': 'NZL',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Panama': 'PAN',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Palau': 'PLW',
    'Papua New Guinea': 'PNG',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Paraguay': 'PRY',
    'Romania': 'ROU',
    'Russian Federation': 'RUS',
    'Rwanda': 'RWA',
    'Saudi Arabia': 'SAU',
    'Sudan': 'SDN',
    'Senegal': 'SEN',
    'Singapore': 'SGP',
    'Solomon Islands': 'SLB',
    'Sierra Leone': 'SLE',
    'El Salvador': 'SLV',
    'San Marino': 'SMR',
    'Somalia': 'SOM',
    'Serbia': 'SRB',
    'South Sudan': 'SSD',
    'Sao Tome and Principe': 'STP',
    'Suriname': 'SUR',
    'Slovak Republic': 'SVK',
    'Slovenia': 'SVN',
    'Sweden': 'SWE',
    'Eswatini': 'SWZ',
    'Sint Maarten (Dutch part)': 'SXM',  # Not an ISO member, placeholder
    'Seychelles': 'SYC',
    'Chad': 'TCD',
    'Togo': 'TGO',
    'Thailand': 'THA',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'Timor-Leste': 'TLS',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkiye': 'TUR',
    'Tuvalu': 'TUV',
    'Tanzania': 'TZA',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'Uruguay': 'URY',
    'United States': 'USA',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'World': 'WLD',  # Not an ISO member, placeholder
    'Samoa': 'WSM',
    'Kosovo': 'XKX',  # Not an ISO member, placeholder
    'Yemen, Rep.': 'YEM',
    'South Africa': 'ZAF',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE'
}

countries_codes_emissoes_co2 = {
    'Afghanistan': 'AFG',
    'Africa': None,
    'Africa (GCP)': None,
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antarctica': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Asia': None,
    'Asia (GCP)': None,
    'Asia (excl. China and India)': None,
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bolivia': 'BOL',
    'Bonaire Sint Eustatius and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Brazil': 'BRA',
    'British Virgin Islands': 'VGB',
    'Brunei': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cape Verde': 'CPV',
    'Central African Republic': 'CAF',
    'Central America (GCP)': None,
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Christmas Island': 'CXR',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Congo': 'COG',
    'Cook Islands': 'COK',
    'Costa Rica': 'CRI',
    "Cote d'Ivoire": 'CIV',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Curacao': 'CUW',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Democratic Republic of Congo': 'COD',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'East Timor': 'TLS',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Europe': None,
    'Europe (GCP)': None,
    'Europe (excl. EU-27)': None,
    'Europe (excl. EU-28)': None,
    'European Union (27)': None,
    'European Union (28)': None,
    'Faroe Islands': 'FRO',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'French Polynesia': 'PYF',
    'Gabon': 'GAB',
    'Gambia': 'GMB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guatemala': 'GTM',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'High-income countries': None,
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'International aviation': None,
    'International shipping': None,
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    'Kosovo': 'XKX',
    'Kuwait': 'KWT',
    'Kuwaiti Oil Fires (GCP)': None,
    'Kyrgyzstan': 'KGZ',
    'Laos': 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Leeward Islands (GCP)': None,
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Low-income countries': None,
    'Lower-middle-income countries': None,
    'Luxembourg': 'LUX',
    'Macao': 'MAC',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands': 'MHL',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mexico': 'MEX',
    'Micronesia (country)': 'FSM',
    'Middle East (GCP)': None,
    'Moldova': 'MDA',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'Niue': 'NIU',
    'Non-OECD (GCP)': None,
    'North America': None,
    'North America (GCP)': None,
    'North America (excl. USA)': None,
    'North Korea': 'PRK',
    'North Macedonia': 'MKD',
    'Norway': 'NOR',
    'OECD (GCP)': None,
    'Oceania': None,
    'Oceania (GCP)': None,
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine': 'PSE',
    'Panama': 'PAN',
    'Panama Canal Zone (GCP)': None,
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Qatar': 'QAT',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Rwanda': 'RWA',
    'Ryukyu Islands (GCP)': None,
    'Saint Helena': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Sint Maarten (Dutch part)': 'SXM',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South America': None,
    'South America (GCP)': None,
    'South Korea': 'KOR',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'St. Kitts-Nevis-Anguilla (GCP)': None,
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syria': 'SYR',
    'Taiwan': 'TWN',
    'Tajikistan': 'TJK',
    'Tanzania': 'TZA',
    'Thailand': 'THA',
    'Togo': 'TGO',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands': 'TCA',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United States': 'USA',
    'Upper-middle-income countries': None,
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'Wallis and Futuna': 'WLF',
    'World': 'WLD',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE'
}

country_codes_precipitacao = {
    'Aruba (Neth.)': 'ABW', 'Afghanistan': 'AFG', 'Angola': 'AGO', 
    'Anguilla (U.K.)': 'AIA', 'Finland': 'FIN', 'Albania': 'ALB', 
    'Andorra': 'AND', 'United Arab Emirates': 'ARE', 'Argentina': 'ARG', 
    'Armenia': 'ARM', 'American Samoa (U.S.)': 'ASM', 
    'French Southern and Antarctic Lands (Fr.)': 'ATF', 
    'Antigua and Barbuda': 'ATG', 'Australia': 'AUS', 'Austria': 'AUT', 
    'Azerbaijan': 'AZE', 'Burundi': 'BDI', 'Belgium': 'BEL', 
    'Benin': 'BEN', 'Bonaire, Sint Eustatius and Saba': 'BES', 
    'Burkina Faso': 'BFA', 'Bangladesh': 'BGD', 'Bulgaria': 'BGR', 
    'Bahrain': 'BHR', 'The Bahamas': 'BHS', 'Bosnia and Herzegovina': 'BIH', 
    'Saint-Barthélemy (Fr.)': 'BLM', 'Belarus': 'BLR', 'Belize': 'BLZ', 
    'Bermuda (U.K.)': 'BMU', 'Bolivia': 'BOL', 'Brazil': 'BRA', 
    'Barbados': 'BRB', 'Brunei Darussalam': 'BRN', 'Bhutan': 'BTN', 
    'Bouvet Island (Nor.)': 'BVT', 'Botswana': 'BWA', 
    'Central African Republic': 'CAF', 'Canada': 'CAN', 
    'Cocos (Keeling) Islands (Aus.)': 'CCK', 'Switzerland': 'CHE', 
    'Chile': 'CHL', 'China': 'CHN', "Côte d'Ivoire": 'CIV', 
    'Cameroon': 'CMR', 'Democratic Republic of Congo': 'COD', 
    'Congo': 'COG', 'Cook Islands (N.Z.)': 'COK', 'Colombia': 'COL', 
    'Comoros': 'COM', 'Cabo Verde': 'CPV', 'Costa Rica': 'CRI', 
    'Cuba': 'CUB', 'Curaçao (Neth.)': 'CUW', 'Christmas Island (Aus.)': 'CXR', 
    'Cayman Islands (U.K.)': 'CYM', 'Cyprus': 'CYP', 'Czech Republic': 'CZE', 
    'Germany': 'DEU', 'Djibouti': 'DJI', 'Dominica': 'DMA', 'Denmark': 'DNK', 
    'Dominican Republic': 'DOM', 'Algeria': 'DZA', 'Ecuador': 'ECU', 
    'Arab Republic of Egypt': 'EGY', 'Eritrea': 'ERI', 'Spain': 'ESP', 
    'Estonia': 'EST', 'Ethiopia': 'ETH', 'Fiji': 'FJI', 'France': 'FRA', 
    'Faroe Islands (Den.)': 'FRO', 'Federated States of Micronesia': 'FSM', 
    'Gabon': 'GAB', 'United Kingdom': 'GBR', 'Georgia': 'GEO', 
    'Guernsey (U.K.)': 'GGY', 'Ghana': 'GHA', 'Gibraltar (U.K.)': 'GIB', 
    'Guinea': 'GIN', 'The Gambia': 'GMB', 'Guinea-Bissau': 'GNB', 
    'Equatorial Guinea': 'GNQ', 'Greece': 'GRC', 'Grenada': 'GRD', 
    'Greenland (Den.)': 'GRL', 'Guatemala': 'GTM', 'Guam (U.S.)': 'GUM', 
    'Guyana': 'GUY', 'Hong Kong, SAR': 'HKG', 
    'Heard Island and McDonald Islands (Aus.)': 'HMD', 
    'Honduras': 'HND', 'Croatia': 'HRV', 'Haiti': 'HTI', 'Hungary': 'HUN', 
    'Indonesia': 'IDN', 'Isle of Man (U.K.)': 'IMN', 'India': 'IND', 
    'British Indian Ocean Territory (U.K.)': 'IOT', 'Ireland': 'IRL', 
    'Islamic Republic of Iran': 'IRN', 'Iraq': 'IRQ', 'Iceland': 'ISL', 
    'Israel': 'ISR', 'Italy': 'ITA', 'Jamaica': 'JAM', 'Jersey (U.K.)': 'JEY', 
    'Jordan': 'JOR', 'Japan': 'JPN', 'Kazakhstan': 'KAZ', 'Kenya': 'KEN', 
    'Kyrgyz Republic': 'KGZ', 'Cambodia': 'KHM', 'Kiribati': 'KIR', 
    'Saint Kitts and Nevis': 'KNA', 'Republic of Korea': 'KOR', 
    'Kosovo': 'XKX', 'Kuwait': 'KWT', "Lao People's Democratic Republic": 'LAO', 
    'Lebanon': 'LBN', 'Liberia': 'LBR', 'Libya': 'LBY', 'Saint Lucia': 'LCA', 
    'Liechtenstein': 'LIE', 'Sri Lanka': 'LKA', 'Lesotho': 'LSO', 
    'Lithuania': 'LTU', 'Luxembourg': 'LUX', 'Latvia': 'LVA', 
    'Macau, SAR': 'MAC', 'Saint-Martin (Fr.)': 'MAF', 'Morocco': 'MAR', 
    'Monaco': 'MCO', 'Moldova': 'MDA', 'Madagascar': 'MDG', 
    'Maldives': 'MDV', 'Mexico': 'MEX', 'Marshall Islands': 'MHL', 
    'North Macedonia': 'MKD', 'Mali': 'MLI', 'Malta': 'MLT', 
    'Myanmar': 'MMR', 'Montenegro': 'MNE', 'Mongolia': 'MNG', 
    'Northern Mariana Islands (U.S.)': 'MNP', 'Mozambique': 'MOZ', 
    'Mauritania': 'MRT', 'Montserrat (U.K.)': 'MSR', 'Mauritius': 'MUS', 
    'Malawi': 'MWI', 'Malaysia': 'MYS', 'Namibia': 'NAM', 
    'New Caledonia (Fr.)': 'NCL', 'Niger': 'NER', 'Norfolk Island (Aus.)': 'NFK', 
    'Nigeria': 'NGA', 'Nicaragua': 'NIC', 'Niue (N.Z.)': 'NIU', 
    'Netherlands': 'NLD', 'Norway': 'NOR', 'Nepal': 'NPL', 'Nauru': 'NRU', 
    'New Zealand': 'NZL', 'Oman': 'OMN', 'Pakistan': 'PAK', 
    'Panama': 'PAN', 'Pitcairn Islands (U.K.)': 'PCN', 'Peru': 'PER', 
    'Philippines': 'PHL', 'Palau': 'PLW', 'Papua New Guinea': 'PNG', 
    'Poland': 'POL', 'Puerto Rico (U.S.)': 'PRI', 'D. P. R. of Korea': 'PRK', 
    'Portugal': 'PRT', 'Paraguay': 'PRY', 'West Bank and Gaza': 'PSE', 
    'French Polynesia (Fr.)': 'PYF', 'Qatar': 'QAT', 'Romania': 'ROU', 
    'Russian Federation': 'RUS', 'Rwanda': 'RWA', 'Saudi Arabia': 'SAU', 
    'Sudan': 'SDN', 'Senegal': 'SEN', 'Singapore': 'SGP', 
    'Saint Helena, Ascension and Tristan da Cunha (U.K.)': 'SHN', 
    'Svalbard and Jan Mayen (Nor.)': 'SJM', 'Solomon Islands': 'SLB', 
    'Sierra Leone': 'SLE', 'El Salvador': 'SLV', 'San Marino': 'SMR', 
    'Somalia': 'SOM', 'Saint-Pierre-et-Miquelon (Fr.)': 'SPM', 
    'Serbia': 'SRB', 'South Sudan': 'SSD', 'São Tomé and Príncipe': 'STP', 
    'Suriname': 'SUR', 'Slovak Republic': 'SVK', 'Slovenia': 'SVN', 
    'Sweden': 'SWE', 'Eswatini': 'SWZ', 'Sint Maarten (Neth.)': 'SXM', 
    'Seychelles': 'SYC', 'Syrian Arab Republic': 'SYR', 
    'Turks and Caicos Islands (U.K.)': 'TCA', 'Chad': 'TCD', 'Togo': 'TGO', 
    'Thailand': 'THA', 'Tajikistan': 'TJK', 'Tokelau (N.Z.)': 'TKL', 
    'Turkmenistan': 'TKM', 'Timor-Leste': 'TLS', 'Tonga': 'TON', 
    'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN', 'Türkiye': 'TUR', 
    'Tuvalu': 'TUV', 'Tanzania': 'TZA', 'Uganda': 'UGA', 'Ukraine': 'UKR', 
    'U.S. Minor Outlying Islands': 'UMI', 'Uruguay': 'URY', 
    'United States of America': 'USA', 'Uzbekistan': 'UZB', 
    'Vatican City': 'VAT', 'Saint Vincent and the Grenadines': 'VCT', 
    'R. B. de Venezuela': 'VEN', 'British Virgin Islands (U.K.)': 'VGB', 
    'United States Virgin Islands (U.S.)': 'VIR', 'Vietnam': 'VNM', 
    'Vanuatu': 'VUT', 'Wallis and Futuna (Fr.)': 'WLF', 
    'Samoa': 'WSM', 'Republic of Yemen': 'YEM', 'South Africa': 'ZAF', 
    'Zambia': 'ZMB', 'Zimbabwe': 'ZWE'
}